// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpzogfgouafmgshuswtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwem9nZmdvdWFmbWdzaHVzd3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzM5ODQsImV4cCI6MjA2MzU0OTk4NH0.gZ0987YmfcwnJGjQqnY45joJvUWdft4rBPxwKZmfk_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);